services:
  db:
    image: postgres:18
    volumes:
      - volumentarea:/var/lib/postgresql


  web:
    build: ../nginx
    container_name: nginx_tarea
    ports:
      - "8080:80"
    networks:
      - redtarea
    volumes:
      - volumentarea:/usr/share/nginx/html

networks:
  redtarea:
    external: true

volumes:
  volumentarea:
    external: true
