services:
  db:
    image: postgres:18
    volumes:
      - volumentarea:/var/lib/postgresql


  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - redtarea
    volumes:
      - ../nginx/html:/usr/share/nginx/html:ro


networks:
  redtarea:
    external: true

volumes:
  volumentarea:
    external: true
