services:
  db:
    image: postgres:18
    container_name: compose-dockerfile-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2123
      POSTGRES_DB: practicaDb
    volumes:
    - volumentarea:/var/lib/postgresql

    networks:
      - redtarea



  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - redtarea
    volumes:
      - ../nginx/html:/usr/share/nginx/html:ro


networks:
  redtarea:
    external: true

volumes:
  volumentarea:
    external: true
